### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by SinTan1071** [MyEtherWallet/MyEtherWallet#1011]
node version 11.14.0
npm version 6.7.0
I installed it successfully, and the log told me:
```ssh
...
Binary found at /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine
npm WARN myetherwallet@5.0.10 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@myetherwallet/mewconnect-web-client/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 4490 packages from 1929 contributors and audited 844788 packages in 817.443s
found 73 vulnerabilities (65 low, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

It seems fine, then I run `npm run build` manually, it just failed:
```ssh
> myetherwallet@5.0.10 build /mnt/d/users/tanrenyuan/Documents/MyEtherWallet
> npm run update && vue-cli-service build


> myetherwallet@5.0.10 update /mnt/d/users/tanrenyuan/Documents/MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.10 update:packages /mnt/d/users/tanrenyuan/Documents/MyEtherWallet
> node package-test.js

new update found moment-timezone 0.5.24 0.5.25 2019-04-18T06:13:15.919Z
new update found @ledgerhq/hw-app-eth 4.53.0 4.54.0 2019-04-19T07:02:12.488Z
new update found @ledgerhq/hw-transport-u2f 4.53.0 4.54.0 2019-04-19T07:02:24.227Z
new update found stylelint 10.0.0 10.0.1 2019-04-16T09:25:43.284Z
new update found stylelint-config-prettier 5.0.0 5.1.0 2019-04-18T19:42:42.794Z
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.10 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.10 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sintan1071/.npm/_logs/2019-04-28T07_30_41_864Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.10 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.10 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sintan1071/.npm/_logs/2019-04-28T07_30_41_929Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.10 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.10 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sintan1071/.npm/_logs/2019-04-28T07_30_41_984Z-debug.log
```
please give me a little help here,, thanks a lot

**Comment by SinTan1071** [comment]
Well, I found something, when I run 'npm install', I thought it works fine and the whole process seems OK, but when I look back for more details on the npm-install log, guess what, I just found something error that I didn't find before:
```ssh
...
> bufferutil@4.0.1 install /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil
> node-gyp-build


> wrtc@0.2.1 install /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.2.1/Release/node-v67-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/node-pre-gyp/lib/install.js:139:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:198:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:447:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:276:11)
node-pre-gyp ERR! System Linux 4.4.0-43-Microsoft
node-pre-gyp ERR! command "/home/sintan1071/.nvm/versions/node/v11.14.0/bin/node" "/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc
node-pre-gyp ERR! node -v v11.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.2.1/Release/node-v67-linux-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4")
Attempting to download WebRTC libraries and headers for platform "linux" and architecture "x64" from

  https://github.com/mayeut/libwebrtc/releases/download/v1.1.1/libwebrtc-1.1.1.60-6294a7eb71c891e9ea41273a7a94113f6802d0da-linux-x64.tar.gz

Complete!
-- Downloading: https://nodejs.org/download/release/v11.14.0/SHASUMS256.txt
-- NodeJS: Using node, version v11.14.0
-- Downloading: https://nodejs.org/download/release/v11.14.0/node-v11.14.0-headers.tar.gz
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build
Running ncmake build
Scanning dependencies of target wrtc
[  5%] Building CXX object CMakeFiles/wrtc.dir/src/binding.cc.o
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h: In lambda function:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/error.h:81:39: error: no matching function for call to ‘v8::Promise::Resolver::Resolve(v8::Local<v8::Value>)’
       resolver->Resolve(tc.Exception()); \
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:64:9: note: in expansion of macro ‘CONVERT_OR_REJECT_AND_RETURN’
         CONVERT_OR_REJECT_AND_RETURN(resolver, error, value, v8::Local<v8::Value>);
         ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/error.h:87:71: error: no matching function for call to ‘v8::Promise::Resolver::Resolve(v8::Local<v8::Value>)’
     resolver->Resolve(Nan::TypeError(Nan::New(error).ToLocalChecked())); \
                                                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:64:9: note: in expansion of macro ‘CONVERT_OR_REJECT_AND_RETURN’
         CONVERT_OR_REJECT_AND_RETURN(resolver, error, value, v8::Local<v8::Value>);
         ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:65:31: error: no matching function for call to ‘v8::Promise::Resolver::Reject(v8::Local<v8::Value>&)’
         resolver->Reject(value);
                               ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4219:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Reject(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Reject(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4219:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h: In lambda function:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/error.h:81:39: error: no matching function for call to ‘v8::Promise::Resolver::Resolve(v8::Local<v8::Value>)’
       resolver->Resolve(tc.Exception()); \
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:67:9: note: in expansion of macro ‘CONVERT_OR_REJECT_AND_RETURN’
         CONVERT_OR_REJECT_AND_RETURN(resolver, result, value, v8::Local<v8::Value>);
         ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/error.h:87:71: error: no matching function for call to ‘v8::Promise::Resolver::Resolve(v8::Local<v8::Value>)’
     resolver->Resolve(Nan::TypeError(Nan::New(error).ToLocalChecked())); \
                                                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:67:9: note: in expansion of macro ‘CONVERT_OR_REJECT_AND_RETURN’
         CONVERT_OR_REJECT_AND_RETURN(resolver, result, value, v8::Local<v8::Value>);
         ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:68:32: error: no matching function for call to ‘v8::Promise::Resolver::Resolve(v8::Local<v8::Value>&)’
         resolver->Resolve(value);
                                ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note: candidate: v8::Maybe<bool> v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>)
     V8_WARN_UNUSED_RESULT Maybe<bool> Resolve(Local<Context> context,
                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4216:39: note:   candidate expects 2 arguments, 1 provided
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventqueue.h:16:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/eventloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/promisefulfillingeventloop.h:16,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/asyncobjectwrapwithloop.h:17,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/datachannel.h:24,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:10:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h: In static member function ‘static std::pair<v8::Local<v8::Promise::Resolver>, std::unique_ptr<node_webrtc::PromiseEvent<T, R, L> > > node_webrtc::PromiseEvent<T, R, L>::Create()’:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/events.h:83:86: error: no matching function for call to ‘v8::Promise::Resolver::New(v8::Isolate*)’
     auto resolver = v8::Promise::Resolver::New(Nan::GetCurrentContext()->GetIsolate());
                                                                                      ^
In file included from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/node.h:63:0,
                 from /mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/src/binding.cc:8:
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4204:55: note: candidate: static v8::MaybeLocal<v8::Promise::Resolver> v8::Promise::Resolver::New(v8::Local<v8::Context>)
     static V8_WARN_UNUSED_RESULT MaybeLocal<Resolver> New(
                                                       ^
/mnt/d/users/tanrenyuan/Documents/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/node/v11.14.0/include/v8.h:4204:55: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
CMakeFiles/wrtc.dir/build.make:62: recipe for target 'CMakeFiles/wrtc.dir/src/binding.cc.o' failed
make[2]: *** [CMakeFiles/wrtc.dir/src/binding.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/wrtc.dir/all' failed
make[1]: *** [CMakeFiles/wrtc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Build failed
Built wrtc
...
```
then 

Is there anyone have the same mistake that happened to me? Any idea how to fix this?

**Comment by WillZhuang** [comment]
the same question.

**Comment by SinTan1071** [comment]
@WillZhuang I update the code this morning, and it works, even though the wrtc error still exist
