### ISSUE TITLE
Unable to Install MyEtherWallet

### ISSUE THREAD

**Issue by tomwalton78** [MyEtherWallet/MyEtherWallet#1182]
- **Bug Report**
  - What is the current behavior?
I am trying to install MyEtherWallet locally by following the Getting Started steps (https://github.com/MyEtherWallet/MyEtherWallet/). However, I am unable to complete this install.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Steps taken:
1. `git clone https://github.com/MyEtherWallet/MyEtherWallet.git`
2. `cd MyEtherWallet/`
3. `npm i`
At this point I start to receive errors. Terminal output is as follows:
```bash
usr@ubuntu:~/Downloads/MyEtherWallet$ npm i
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
usr@ubuntu:~/Downloads/MyEtherWallet$ npm i
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.1.0 requires a peer of eslint@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN truffle-hdwallet-provider@0.0.6 requires a peer of truffle@4.x but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN myetherwallet@5.0.13 No license field.

audited 829351 packages in 32.794s
found 66 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
usr@ubuntu:~/Downloads/MyEtherWallet$ npm run build

> myetherwallet@5.0.13 build /home/usr/Downloads/MyEtherWallet
> npm run update && vue-cli-service build


> myetherwallet@5.0.13 update /home/usr/Downloads/MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.13 update:packages /home/usr/Downloads/MyEtherWallet
> node package-test.js

new update found vee-validate 2.2.9 2.2.10 2019-06-08T13:50:32.662Z
new update found ethereumjs-tx 1.3.7 2.0.0 2019-06-07T08:20:29.213Z
new update found prettier 1.17.1 1.18.2 2019-06-07T14:55:43.212Z
new update found secp256k1 3.7.0 3.7.1 2019-05-31T10:12:55.374Z
new update found stylelint 10.0.1 10.1.0 2019-06-07T14:31:44.418Z
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.13 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.13 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-18T15_56_26_470Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.13 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.13 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-18T15_56_26_495Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.13 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-18T15_56_26_515Z-debug.log

```

As can be seen from above, the "npm ERR! cb() never called!" error does not happen again the next time the `npm i` command is run.

  - Please tell us about your environment:
    - Operating system: Ubuntu 18.04.2 LTS, inside a virtualbox virtual machine
    - nodejs: v8.16.0
    - npm: v6.4.1

I would be very grateful if someone could assist me with this?

**Comment by gamalielhere** [comment]
@tomwalton78 As the error suggests, please update your package.json with the proper versions:
```
new update found vee-validate 2.2.9 2.2.10 2019-06-08T13:50:32.662Z
new update found ethereumjs-tx 1.3.7 2.0.0 2019-06-07T08:20:29.213Z
new update found prettier 1.17.1 1.18.2 2019-06-07T14:55:43.212Z
new update found secp256k1 3.7.0 3.7.1 2019-05-31T10:12:55.374Z
new update found stylelint 10.0.1 10.1.0 2019-06-07T14:31:44.418Z
```

<package name> <current package version> <version to update to>

**Comment by tomwalton78** [comment]
@gamalielhere 

Thank you. I updated the package.json file in the MyEtherWallet directory with the newer versions, however now I receive new errors. This is my terminal output:

```bash
usr@ubuntu:~/Downloads/MyEtherWallet$ npm i

> secp256k1@3.7.1 install /home/usr/Downloads/MyEtherWallet/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild /home/usr/Downloads/MyEtherWallet/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/home/usr/Downloads/MyEtherWallet/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
../src/privatekey.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE privateKeyNegate(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/privatekey.cc:73:30: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
   secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/home/usr/Downloads/MyEtherWallet/node_modules/secp256k1/build'
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.1.0 requires a peer of eslint@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN truffle-hdwallet-provider@0.0.6 requires a peer of truffle@4.x but none is installed. You must install peer dependencies yourself.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN myetherwallet@5.0.13 No license field.

added 11 packages from 11 contributors, removed 3 packages, updated 12 packages and audited 829352 packages in 42.126s
found 66 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
usr@ubuntu:~/Downloads/MyEtherWallet$ npm run build

> myetherwallet@5.0.13 build /home/usr/Downloads/MyEtherWallet
> npm run update && vue-cli-service build


> myetherwallet@5.0.13 update /home/usr/Downloads/MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.13 update:packages /home/usr/Downloads/MyEtherWallet
> node package-test.js


> myetherwallet@5.0.13 update:lists /home/usr/Downloads/MyEtherWallet
> node fetchLists/index.js

Writing tokens for the network: akroma
Writing tokens for the network: ath
Writing tokens for the network: clo
Writing tokens for the network: egem
Writing tokens for the network: ella
Writing tokens for the network: esn
Writing tokens for the network: etc
Writing tokens for the network: eth
Writing tokens for the network: etho
Writing tokens for the network: etsc
Writing tokens for the network: exp
Writing tokens for the network: go
Writing tokens for the network: goerli
Writing tokens for the network: iolite
Writing tokens for the network: kov
Writing tokens for the network: mix
Writing tokens for the network: music
Writing tokens for the network: pirl
Writing tokens for the network: poa
Writing tokens for the network: reosc
Writing tokens for the network: rin
Writing tokens for the network: rop
Writing tokens for the network: rsk-test
Writing tokens for the network: rsk
Writing tokens for the network: tomo
Writing tokens for the network: tt
Writing tokens for the network: ubq
Writing tokens for the network: web
Writing contract for the network: akroma
Writing contract for the network: ath
Writing contract for the network: clo
Writing contract for the network: egem
Writing contract for the network: ella
Writing contract for the network: esn
Writing contract for the network: etc
Writing contract for the network: eth
Writing contract for the network: etho
Writing contract for the network: etsc
Writing contract for the network: exp
Writing contract for the network: go
Writing contract for the network: goerli
Writing contract for the network: iolite
Writing contract for the network: kov
Writing contract for the network: mix
Writing contract for the network: music
Writing contract for the network: pirl
Writing contract for the network: poa
Writing contract for the network: reosc
Writing contract for the network: rin
Writing contract for the network: rop
Writing contract for the network: rsk-test
Writing contract for the network: rsk
Writing contract for the network: tomo
Writing contract for the network: tt
Writing contract for the network: ubq
Writing contract for the network: web
writing darklist
Done
sh: 1: vue-cli-service: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! myetherwallet@5.0.13 build: `npm run update && vue-cli-service build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-18T16_17_13_795Z-debug.log

```

**Comment by gamalielhere** [comment]
@tomwalton78 can you install `@vue/cli` globally?

**Comment by tomwalton78** [comment]
So I installed @vue/cli-service with: npm install -g @vue/cli-service and that fixed that error.
I had similar errors with other packages, so I fixed those by installing:
- npm install -g @vue/cli-service
- npm install -g @vue/cli-plugin-babel
- npm install -g @vue/cli-plugin-eslint
- npm install -g @vue/cli-plugin-pwa
- npm install -g @vue/cli-plugin-unit-jest
- npm install -g vue-template-compiler

Now I have an error about running out of memory, which seems odd to me, since I am running this on a machine with 12 GB of memory:

```
usr@ubuntu:~/Downloads/MyEtherWallet$ npm run build

> myetherwallet@5.0.13 build /home/usr/Downloads/MyEtherWallet
> npm run update && vue-cli-service build


> myetherwallet@5.0.13 update /home/usr/Downloads/MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.13 update:packages /home/usr/Downloads/MyEtherWallet
> node package-test.js


> myetherwallet@5.0.13 update:lists /home/usr/Downloads/MyEtherWallet
> node fetchLists/index.js

Writing tokens for the network: akroma
Writing tokens for the network: ath
Writing tokens for the network: clo
Writing tokens for the network: egem
Writing tokens for the network: ella
Writing tokens for the network: esn
Writing tokens for the network: etc
Writing tokens for the network: eth
Writing tokens for the network: etho
Writing tokens for the network: etsc
Writing tokens for the network: exp
Writing tokens for the network: go
Writing tokens for the network: goerli
Writing tokens for the network: iolite
Writing tokens for the network: kov
Writing tokens for the network: mix
Writing tokens for the network: music
Writing tokens for the network: pirl
Writing tokens for the network: poa
Writing tokens for the network: reosc
Writing tokens for the network: rin
Writing tokens for the network: rop
Writing tokens for the network: rsk-test
Writing tokens for the network: rsk
Writing tokens for the network: tomo
Writing tokens for the network: tt
Writing tokens for the network: ubq
Writing tokens for the network: web
Writing contract for the network: akroma
Writing contract for the network: ath
Writing contract for the network: clo
Writing contract for the network: egem
Writing contract for the network: ella
Writing contract for the network: esn
Writing contract for the network: etc
Writing contract for the network: eth
Writing contract for the network: etho
Writing contract for the network: etsc
Writing contract for the network: exp
Writing contract for the network: go
Writing contract for the network: goerli
Writing contract for the network: iolite
Writing contract for the network: kov
Writing contract for the network: mix
Writing contract for the network: music
Writing contract for the network: pirl
Writing contract for the network: poa
Writing contract for the network: reosc
Writing contract for the network: rin
Writing contract for the network: rop
Writing contract for the network: rsk-test
Writing contract for the network: rsk
Writing contract for the network: tomo
Writing contract for the network: tt
Writing contract for the network: ubq
Writing contract for the network: web
writing darklist
Done

⠙  Building for production...(node:3034) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
⠧  Building for production...
<--- Last few GCs --->

[3034:0x311a700]   193211 ms: Mark-sweep 1334.9 (1457.4) -> 1334.8 (1459.9) MB, 929.6 / 0.0 ms  allocation failure GC in old space requested
[3034:0x311a700]   193855 ms: Mark-sweep 1334.8 (1459.9) -> 1334.8 (1428.9) MB, 643.9 / 0.0 ms  last resort GC in old space requested
[3034:0x311a700]   194642 ms: Mark-sweep 1334.8 (1428.9) -> 1334.8 (1428.9) MB, 787.4 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x39e6de625891 <JSObject>
    1: addMappingWithCode [/usr/lib/node_modules/@vue/cli-service/node_modules/source-map/lib/source-node.js:~150] [pc=0x3b49d842266](this=0x807c5c0c2f1 <JSGlobal Object>,mapping=0x2801dd348d91 <Object map = 0x83db7da2969>,code=0xff1d2299621 <String[4]: new >)
    2: /* anonymous */ [/usr/lib/node_modules/@vue/cli-service/node_modules/source-map/lib/source-node.js:~86] [pc=0x3b49d83fdcd](this=0x...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8cd14c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xd83553 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x3b49c3842fd
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! myetherwallet@5.0.13 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-18T18_17_30_383Z-debug.log
```

**Comment by tomwalton78** [comment]
After further research I have managed to fix the out of memory issue via:
export NODE_OPTIONS=--max_old_space_size=8192

Then I needed to rebuild several modules in order to progress past some other error messages:
npm rebuild node-sass
npm rebuild optipng-bin
npm rebuild jpegtran-bin
npm rebuild mozjpeg

Now I am encountering a rather vague error message upon running `npm run build`. More specifically, this message appears as a result of the `vue-cli-service build` command. Any ideas?

```
⠙  Building for production...(node:2321) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 ERROR  Error
Error
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.14-hotfix.2 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.14-hotfix.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/usr/.npm/_logs/2019-06-26T16_28_51_389Z-debug.log

```

**Comment by tomwalton78** [comment]
I have now finally managed to get the install to work. Below is all of the steps I took to overcome the various errors that occurred.

Follow install steps given on GitHub README

(1)
If `npm i` fails the first time, try running command again.

(2)
Need to install these packages:
npm install -g @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint @vue/cli-plugin-pwa @vue/cli-plugin-unit-jest vue-template-compiler opencollective

(3) https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory
export NODE_OPTIONS=--max_old_space_size=8192

(4) https://github.com/sass/node-sass/issues/1579
npm update
npm install
nodejs node_modules/node-sass/scripts/install.js
npm rebuild node-sass <- should be the important one

(5) https://github.com/imagemin/optipng-bin/issues/84
npm rebuild optipng-bin
npm rebuild jpegtran-bin
npm rebuild mozjpeg

(6)
If complains about deleting node_modules/websocket, delete it manually

(7) npm rebuild not working
Edit package.json to contain latest version of "canvas" package
npm i
npm rebuild

npm run build
npm start

**Comment by orangemio** [comment]
what's your node version ?

**Comment by ClarenceL** [comment]
I just finally got this to work on v9.10.1 - thanks! The `npm rebuild` was really much needed.

**Comment by interfect** [comment]
@tomwalton78 Did you ever make a PR to add `export NODE_OPTIONS=--max_old_space_size=8192` into the build documentation in the README? I tried to follow it and ran out of memory too. It seems the build won't work by default, although `NODE_OPTIONS=--max_old_space_size=2048` is sufficient for me.

**Comment by rfcid** [comment]
0x82614c37d48c0483DEb0623AA52E47EB30BfA955

2020-01-12 3:14 GMT+02:00, interfect <notifications@github.com>:

**Comment by TeslaZhou-Xin** [comment]
I have been repeating the installation all day, and I narrowly think that this project is not open source, it may be deceptive! ! ! 🤣

**Comment by rdotterer09** [comment]
I can’t access my wallet at this time I am a truck driver and my recovery phrase is at home, please don’t shut down my account for inactivity

**Comment by interfect** [comment]
@rdotterer09 It's not possible for MEW or anyone else to shut down your wallet for inactivity, and anyone telling you otherwise is probably doing it to create a sense of urgency for a scam.

**Comment by rdotterer09** [comment]
Ok thank you

**Comment by kingaj12** [comment]
I followed @tomwalton78 post (thanks!) and it worked mostly quite well.  In step (7) there were a few other out of date packages, but quite easy to fix.  I had to run `npm run build` a couple of times.

**Comment by KONG41** [comment]
$ npm start

> myetherwallet@6.7.2 start
> npm run update:mainlists && npm run dev


> myetherwallet@6.7.2 update:mainlists
> node fetchLists/fetchMainLists.js

node:internal/modules/cjs/loader:1024
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- F:\cash-study-project\MyEtherWallet\fetchLists\fetchMainLists.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (F:\cash-study-project\MyEtherWallet\fetchLists\fetchMainLists.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\cash-study-project\\MyEtherWallet\\fetchLists\\fetchMainLists.js'
  ]
}

**Comment by robespierre81** [comment]
Hey,

I just made a fork for myself. Actually I am running in the following error and don't know how to solve it. Several ideas I read about issues with the starting of the wallet server didn't work:
` INFO  Starting development server...
10% building 2/4 modules 2 active node_modules/webpack-dev-server/client/index.js?https://localhost:8080&sockPath=/sockjs-nodenode:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/bodi/Desktop/WalterOliver/amura/Wallet.Amura/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.4.0
npm verb exit 1
npm verb code 1
npm verb exit 1`

**Comment by peterr101** [comment]
How do I add a test account for development so I can add fake amounts?

**Comment by kittykillenit** [comment]
I did something with vechain not sure what anyone know about that it was like 2018 or 2016

**Comment by Maliksb11** [comment]
Ok 👍
