### ISSUE TITLE
Commit hook tests do not pass out of the box

### ISSUE THREAD

**Issue by interfect** [MyEtherWallet/MyEtherWallet#1846]
- **I'm submitting a ...**

  - [ ] Feature request
  - [X] Bug report

- **Bug Report**
  - What is the current behavior?
    - Commit hooks do not pass out of the box.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
    - Install NodeJS v11.15.0 and npm 6.7.0 (using `n`) on Ubuntu 18.04, along with `build-essential`.
    - `git clone https://github.com/MyEtherWallet/MyEtherWallet.git`
    - `cd MyEtherWallet`
    - `git fetch origin && git checkout origin/develop`
    - `npm install` (Note that this command succeeds! Installation is supposedly successful, despite the many pages of output.)
    - `touch a`
    - `git add a`
    - `git commit -m "Test"`
  - What is the expected behavior?
    - The commit hook tests should succeed out of the box on a trivial commit like this.
  - What is the motivation / use case for changing the behavior?
    - If the commit hooks do not work, everyone will have to bypass them. Then they won't enforce anything they are meant to enforce.
  - Please tell us about your environment:
    - Operating system
      - Ubuntu 18.04
    - Browser and version
      - N/A
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
    Pretty much all the tests fail with `Unable to find native module` on `import MEWconnect from '@myetherwallet/mewconnect-web-client';`. Presumably that failed to build during `npm install`, but additional runs of `npm install` do not seem to try to build it again.
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

I won't paste the entire enormous log of 100+ failed tests, but here's the end of it:

```
 FAIL  tests/unit/specs/src/components/BottomHelpLink/BottomHelpLink.spec.js
  ● Test suite failed to run

    Unable to find native module

    > 1 | import MEWconnect from '@myetherwallet/mewconnect-web-client';
        | ^
      2 | import store from '@/store';
      3 | import { Transaction } from 'ethereumjs-tx';
      4 | import WalletInterface from '@/wallets/WalletInterface';

      at requireNativeModule (node_modules/@myetherwallet/mewconnect-web-client/node_modules/node-cmake/index.js:40:20)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/lib/binding.js:3:39)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/lib/index.js:3:15)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/dist/index.js:12:28)
      at Object.<anonymous> (src/wallets/hybrid/MEWconnect/index.js:1:1)
      at Object.<anonymous> (src/wallets/hybrid/index.js:1:1)
      at Object.<anonymous> (src/wallets/index.js:10:1)
      at Object.<anonymous> (src/helpers/ExtensionHelpers.js:3:1)
      at Object.<anonymous> (src/helpers/index.js:9:1)
      at Object.<anonymous> (src/directives/AddrResolver.js:2:1)
      at Object.<anonymous> (tests/unit/helpers/setupTooling.js:9:1)
      at Object.<anonymous> (tests/unit/helpers/index.js:2:1)
      at Object.<anonymous> (tests/unit/specs/src/components/BottomHelpLink/BottomHelpLink.spec.js:3:1)

 FAIL  tests/unit/specs/src/layouts/HomeLayout/HomeLayout.spec.js
  ● Test suite failed to run

    Unable to find native module

    > 1 | import MEWconnect from '@myetherwallet/mewconnect-web-client';
        | ^
      2 | import store from '@/store';
      3 | import { Transaction } from 'ethereumjs-tx';
      4 | import WalletInterface from '@/wallets/WalletInterface';

      at requireNativeModule (node_modules/@myetherwallet/mewconnect-web-client/node_modules/node-cmake/index.js:40:20)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/lib/binding.js:3:39)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/lib/index.js:3:15)
      at Object.<anonymous> (node_modules/@myetherwallet/mewconnect-web-client/dist/index.js:12:28)
      at Object.<anonymous> (src/wallets/hybrid/MEWconnect/index.js:1:1)
      at Object.<anonymous> (src/wallets/hybrid/index.js:1:1)
      at Object.<anonymous> (src/wallets/index.js:10:1)
      at Object.<anonymous> (src/helpers/ExtensionHelpers.js:3:1)
      at Object.<anonymous> (src/helpers/index.js:9:1)
      at Object.<anonymous> (src/store/mutations.js:2:1)
      at Object.<anonymous> (src/store/index.js:4:1)
      at Object.<anonymous> (src/helpers/addressUtils.js:1:1)
      at Object.<anonymous> (src/helpers/misc.js:3:1)
      at src/components/CustomerSupport/CustomerSupport.vue:1277:50
      at Object.<anonymous> (src/components/CustomerSupport/CustomerSupport.vue:1420:3)
      at Object.<anonymous> (src/components/CustomerSupport/index.js:1:1)
      at src/containers/FaqsContainer/FaqsContainer.vue:589:49
      at Object.<anonymous> (src/containers/FaqsContainer/FaqsContainer.vue:715:3)
      at Object.<anonymous> (src/containers/FaqsContainer/index.js:1:1)
      at src/layouts/HomeLayout/HomeLayout.vue:461:50
      at Object.<anonymous> (src/layouts/HomeLayout/HomeLayout.vue:512:3)
      at Object.<anonymous> (tests/unit/specs/src/layouts/HomeLayout/HomeLayout.spec.js:2:1)


Test Suites: 116 failed, 4 skipped, 6 passed, 122 of 126 total
Tests:       8 skipped, 6 passed, 14 total
Snapshots:   0 total
Time:        44.044s
Ran all test suites.
Skipped 8 specs in 5 suites
  Skipped 4 specs in /z/home/anovak/workspace/MyEtherWallet/tests/unit/specs/src/partners/kyber/kyber.spec.js
    - kyber.js should return the value in token wei
    - kyber.js should return gas limits array from api
    - kyber.js should return data for kyber trade tx
    - kyber.js should return data for kyber approval tx
  Skipped 1 specs in /z/home/anovak/workspace/MyEtherWallet/tests/unit/specs/src/partners/changelly/changelly.spec.js
    - changelly.js Expect fixed rate calculated value to be within 1% of exact value (from ETH) 
  Skipped 1 specs in /z/home/anovak/workspace/MyEtherWallet/tests/unit/specs/src/layouts/InterfaceLayout/InterfaceLayout.spec.js
    - InterfaceLayout.vue should render correct balance data
  Skipped 1 specs in /z/home/anovak/workspace/MyEtherWallet/tests/unit/specs/src/partners/simplex/simplex-api.spec.js
    - simplex.js [INTENTIONALLY SKIPPED] should instanciate a new instance
  Skipped 1 specs in /z/home/anovak/workspace/MyEtherWallet/tests/unit/specs/src/partners/simplex/simplex.spec.js
    - simplex.js [INTENTIONALLY SKIPPED] should instanciate a new instance
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.2.9 test:unit: `vue-cli-service test:unit --logHeapUsage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.2.9 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /z/home/anovak/.npm/_logs/2020-01-11T23_40_35_703Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.2.9 test: `npm run update:lists && jest --clearCache && npm run test:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.2.9 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /z/home/anovak/.npm/_logs/2020-01-11T23_40_35_718Z-debug.log

pre-commit hook failed (add --no-verify to bypass)
```

**Comment by gamalielhere** [comment]
closing as this has been fixed
