### ISSUE TITLE
Ubuntu Install Problem

### ISSUE THREAD

**Issue by bilogate** [MyEtherWallet/MyEtherWallet#1974]
i cant install mew on my linux box
After this error i cant try to reinstall , After npm run build command it says complete done but nothing is happing. 
I have tryed npm install -g increase-memory-limit and increase-memory-limit but no luck again 

Distro: ubuntu 18 .04
Node: v10.15.3
Npm: 6.4.1
Problem : npm run build

> myetherwallet@5.3.2 update:swap /root/w/MyEtherWallet
> node compileBaseSwapOptions.js

Complete

⠴  Building for production...
<--- Last few GCs --->

[24661:0x27b20a0]   226437 ms: Mark-sweep 995.3 (1267.1) -> 995.3 (1246.1) MB, 652.3 / 0.0 ms  (average mu = 0.412, current mu = 0.010) last resort GC in old space requested
[24661:0x27b20a0]   227096 ms: Mark-sweep 995.3 (1246.1) -> 995.3 (1227.1) MB, 659.0 / 0.0 ms  (average mu = 0.250, current mu = 0.000) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x11e47c6dbe1d]
Security context: 0x164e8061e6e9 <JSObject>
    1: _send [0x2dd0405406c9] [internal/child_process.js:724] [bytecode=0x2264d75f40e1 offset=607](this=0x1c122ec96c59 <ChildProcess map = 0x1be947356fd1>,message=0x163b5fc91b89 <JSArray[4]>,handle=0x33b8143026f1 <undefined>,options=0x163b5fc91c11 <Object map = 0x1500c19cc291>,callback=0x33b8143026f1 <undefined>)
    2: send [0x2dd040540671] [internal/child_...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [node]
 2: 0x8dc55c  [node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec7bf2  [node]
 6: 0xed740f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 7: 0xea6fbb v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 8: 0xff08b3 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 9: 0xad7184 v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
10: 0xae4f10 v8::String::Utf8Length() const [node]
11: 0x99f781 node::StringBytes::Size(v8::Isolate*, v8::Local<v8::Value>, node::encoding) [node]
12: 0x9a833d int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
13: 0x9af372 void node::StreamBase::JSMethod<node::LibuvStreamWrap, &(int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&))>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
14: 0xb62a3f  [node]
15: 0xb635a9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
16: 0x11e47c6dbe1d
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! myetherwallet@5.3.2 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the myetherwallet@5.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-14T05_51_58_251Z-debug.log

**Comment by bilogate** [comment]
I guess i have resolved Allocation failed - JavaScript heap out of memory error with this command
export NODE_OPTIONS=--max-old-space-size=8192
but now it gives

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myetherwallet@5.3.2~prebuild: myetherwallet@5.3.2
6 info lifecycle myetherwallet@5.3.2~build: myetherwallet@5.3.2
7 verbose lifecycle myetherwallet@5.3.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle myetherwallet@5.3.2~build: PATH: /root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/w/MyEtherWallet/node_modules/.bin:/root/.nvm/versions/node/v10.15.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/root/work/bin
9 verbose lifecycle myetherwallet@5.3.2~build: CWD: /root/w/MyEtherWallet
10 silly lifecycle myetherwallet@5.3.2~build: Args: [ '-c', 'npm run update && vue-cli-service build' ]
11 silly lifecycle myetherwallet@5.3.2~build: Returned: code: 137  signal: null
12 info lifecycle myetherwallet@5.3.2~build: Failed to exec build script
13 verbose stack Error: myetherwallet@5.3.2 build: `npm run update && vue-cli-service build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid myetherwallet@5.3.2
15 verbose cwd /root/w/MyEtherWallet
16 verbose Linux 4.4.0-173-generic
17 verbose argv "/root/.nvm/versions/node/v10.15.3/bin/node" "/root/.nvm/versions/node/v10.15.3/bin/npm" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 137
22 error myetherwallet@5.3.2 build: `npm run update && vue-cli-service build`
22 error Exit status 137
23 error Failed at the myetherwallet@5.3.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by bilogate** [comment]
Update
After add 4 gb more ram to my vps errors are changed. I have wait like 20min npm build install and gave this error :(

⠇  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                                                                            2:33:56 PM

 error

js/vendors.45cf1593.js from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/root/ww/MyEtherWallet/node_modules/@vue/cli-service/node_modules/jest-worker/build/workers/ChildProcessWorker.js:230:21)
    at ChildProcessWorker._onExit (/root/ww/MyEtherWallet/node_modules/@vue/cli-service/node_modules/jest-worker/build/workers/ChildProcessWorker.js:307:12)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.3.2 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-14T14_33_56_704Z-debug.log

**Comment by bilogate** [comment]
Again Update:
I ignore the preview error and try to start mew with npm start but it starting dev mode not production mode. I have clone production mode not dev.  I didnt use this command npm run dev
it says;

 App running at:
  - Local:   https://localhost:8080
  - Network: https://localhost:8080

  Note that the development build is not optimized.
  To create a production build, run npm run build.

after npm run build its same , dev mode starting again.

**Comment by bilogate** [comment]
I have fixed all error just there is one 
npm run starting development server but tutorial says it will start production server.
how can i run production server ?
