### ISSUE TITLE
npm ci fails with EUSAGE

### ISSUE THREAD

**Issue by ChuckNorrison** [MyEtherWallet/MyEtherWallet#4615]
###### Info

- **Version**: Current sources
- **Browser**: -
- **OS**: Ubuntu 22.04
- **Page Url**: -

###### Steps to reproduce

`git clone`
`npm ci`

###### What do you expect to happen?

Build success

###### What happens instead?

> npm ERR! code EUSAGE
> npm ERR! 
> npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> npm ERR! 
> npm ERR! Invalid: lock file's axios@0.27.2 does not satisfy axios@0.21.4
> npm ERR! Invalid: lock file's protobufjs@7.2.0 does not satisfy protobufjs@6.11.3
> npm ERR! Missing: keccak@3.0.3 from lock file
> ...

**Comment by akvlad** [comment]
Same here 
1. `npm ERR! code EUSAGE` 
2. After `npm install`  another set of errors:
> ERROR: Update @coolwallet/eth from 1.1.16 to 1.1.19. Released: 2023-06-19T10:02:59.885Z
ERROR: Update @sentry/browser from 7.54.0 to 7.57.0. Released: 2023-06-28T15:27:04.479Z
ERROR: Update @sentry/tracing from 7.54.0 to 7.57.0. Released: 2023-06-28T15:27:04.555Z
ERROR: Update @sentry/vue from 7.54.0 to 7.57.0. Released: 2023-06-28T15:27:04.742Z
ERROR: Update @commitlint/config-conventional from 17.6.5 to 17.6.6. Released: 2023-06-24T08:48:16.760Z
ERROR: Update commitlint from 17.6.5 to 17.6.6. Released: 2023-06-24T08:48:21.682Z
ERROR: Update protobufjs from 7.2.3 to 7.2.4. Released: 2023-06-27T17:05:27.434Z

3. Then There's a set of errors like:
> npm ERR! While resolving: myetherwallet@6.7.4
npm ERR! Found: graphql@15.5.3

4. After `npm update --force` I have:
5. `npm run build`  I have a set of errors like this
> FetchError: invalid json response body at https://api.1inch.exchange/v3.0/1/tokens reason: Unexpected token < in JSON at position 0
    at /home/hromozeka/MyEtherWallet/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getFormattedList (/home/hromozeka/MyEtherWallet/fetchLists/index.js:17:16)
    at async fetchOneInchLists (/home/hromozeka/MyEtherWallet/fetchLists/index.js:35:21)
    at async fetchMasterFile (/home/hromozeka/MyEtherWallet/fetchLists/index.js:115:27)
    at async run (/home/hromozeka/MyEtherWallet/fetchLists/index.js:208:3)
    at async /home/hromozeka/MyEtherWallet/fetchLists/index.js:213:5 {
  type: 'invalid-json'
}
Done

>⠸  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/hromozeka/MyEtherWallet/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/hromozeka/MyEtherWallet/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠇  Building for production.../home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

> Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/hromozeka/MyEtherWallet/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/hromozeka/MyEtherWallet/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/hromozeka/MyEtherWallet/node_modules/cache-loader/dist/index.js:147:7
    at /home/hromozeka/MyEtherWallet/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by kanna5** [comment]
To build this you will need Node.js 14 with npm 6, and Python 3.10 or lower.
