### ISSUE TITLE
TypeError: 'defineProperty' on proxy: trap returned falsish for property '__ob__'

### ISSUE THREAD

**Issue by wojijiwo** [MyEtherWallet/MyEtherWallet#4828]
###### Info

- **Version**: commit 52ea653a20f37becec7aa01f2564370f4366c8b1, [latest commit](https://github.com/MyEtherWallet/MyEtherWallet/commit/52ea653a20f37becec7aa01f2564370f4366c8b1)
- **Browser**: Chrome
- **OS**: macOS Ventura 13.4
- **Page Url**: https://localhost:8080/#/
- **Node**: 12.22.3
- **Npm**: v6.14.13
- **Chrome**: Version 120.0.6099.216 (Official Build) (arm64)
- **Firefox**: 122.0 (64-bit)
- **Brave Browser**: [Version 1.61.120 Chromium: 120.0.6099.234 (Official Build) (arm64)](https://brave.com/latest/)

###### Steps to reproduce

1. Git clone latest with commit 52ea653a20f37becec7aa01f2564370f4366c8b1
2. npm ci
3. npm update
4. npm run dev

###### What do you expect to happen?

Open https://localhost:8080/#/ in Chrome, it reports 

sentry.js:19 TypeError: 'defineProperty' on proxy: trap returned falsish for property '__ob__'
    at Function.defineProperty (<anonymous>)
    at def (vue.runtime.esm.js:483:1)
    at new Observer (vue.runtime.esm.js:911:1)
    at observe (vue.runtime.esm.js:988:1)
    at defineReactive$$1 (vue.runtime.esm.js:1020:1)
    at Observer.walk (vue.runtime.esm.js:932:1)
    at new Observer (vue.runtime.esm.js:920:1)
    at observe (vue.runtime.esm.js:988:1)
    at Observer.observeArray (vue.runtime.esm.js:941:1)
    at Array.mutator (vue.runtime.esm.js:880:20)
    at Store.STORE_EIP6963_WALLET (mutations.js:39:12)
    at wrappedMutationHandler (vuex.esm.js:844:1)
    at commitIterator (vuex.esm.js:466:1)
    at Array.forEach (<anonymous>)
    at vuex.esm.js:465:1
    at Store._withCommit (vuex.esm.js:624:1)
    at Store.commit (vuex.esm.js:464:1)
    at Store.boundCommit [as commit] (vuex.esm.js:409:1)
    at local.commit (vuex.esm.js:796:1)
    at Store.storeEIP6963Wallet (actions.js:224:3)
    at Array.wrappedActionHandler (vuex.esm.js:851:1)
    at Store.dispatch (vuex.esm.js:516:1)
    at Store.boundDispatch [as dispatch] (vuex.esm.js:406:1)
    at local.dispatch (vuex.esm.js:779:1)
    at VueComponent.mappedAction (vuex.esm.js:1064:1)
    at VueComponent.mounted (mainApp.vue:87:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at callHook (vue.runtime.esm.js:4235:1)
    at Object.insert (vue.runtime.esm.js:3158:1)
    at invokeInsertHook (vue.runtime.esm.js:6390:1)
    at Vue.patch [as __patch__] (vue.runtime.esm.js:6609:1)
    at Vue._update (vue.runtime.esm.js:3960:1)
    at Vue.updateComponent (vue.runtime.esm.js:4081:1)
    at Watcher.get (vue.runtime.esm.js:4495:1)
    at new Watcher (vue.runtime.esm.js:4484:1)
    at mountComponent (vue.runtime.esm.js:4088:1)
    at ./node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (vue.runtime.esm.js:8459:1)
    at Vue._init (vue.runtime.esm.js:5032:1)
    at new Vue (vue.runtime.esm.js:5099:1)
    at ./src/main/liveMain.js (liveMain.js:85:1)
    at __webpack_require__ (bootstrap:832:1)
    at fn (bootstrap:129:1)

But in Firefox, Brave Browser, Opera, it all not report such error.

###### What happens instead?

Should not report such error.

###### Screenshot

<img width="1271" alt="image" src="https://github.com/MyEtherWallet/MyEtherWallet/assets/76248214/c83f5de9-d727-4031-aa74-ff2aab03eca3">

**Comment by gamalielhere** [comment]
Can't seem to replicate this, can you pull `develop` branch and try it?
