### ISSUE TITLE
`npm run-script build` fails

### ISSUE THREAD

**Issue by DreamFlasher** [MyEtherWallet/MyEtherWallet#671]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
`npm run-script build` yields
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.2 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.2 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-18T18_47_30_919Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.2 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.2 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-18T18_47_30_980Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.2 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-18T18_47_31_030Z-debug.log
```

`cat  /root/.npm/_logs/2019-02-18T18_47_30_919Z-debug.log` yields:

```
13 verbose stack Error: myetherwallet@5.0.2 update:packages: `node package-test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid myetherwallet@5.0.2
15 verbose cwd /root/git/MyEtherWallet
16 verbose Linux 4.4.0-17763-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "update:packages"
18 verbose node v9.11.2
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.2 update:packages: `node package-test.js`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.2 update:packages script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

OS: Windows Ubuntu Bash, also tried on standard Ubuntu 18.04, same error

**Comment by gamalielhere** [comment]
@DreamFlasher can you try copying the current `package.json` we have on `develop` branch? Also, make sure you have our `package-test.js` file.

**Comment by DreamFlasher** [comment]
Shall I checkout the `develop` branch and work with this?

**Comment by gamalielhere** [comment]
@DreamFlasher If possible yes. That's where our changes will be until release. Also, just to make sure, did you run `npm install` before `npm run build`?

**Comment by DreamFlasher** [comment]
I run `npm install` succesfully before, yes. On the `develop` branch when I run `npm run-script build` I get:
```
> myetherwallet@5.0.2 build /root/git/MyEtherWallet2
> npm run update && vue-cli-service build


> myetherwallet@5.0.2 update /root/git/MyEtherWallet2
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.2 update:packages /root/git/MyEtherWallet2
> node package-test.js

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'package-json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/root/git/MyEtherWallet2/package-test.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by gamalielhere** [comment]
@DreamFlasher can you check if you have the `package-test.js` file?

**Comment by DreamFlasher** [comment]
yes, it's there.

**Comment by gamalielhere** [comment]
@DreamFlasher try running `npm install` again. This error is happening when they package isn't there. Which in this case `package-json` isn't installed.

**Comment by DreamFlasher** [comment]
Now it fails with:

`cat /root/.npm/_logs/2019-02-19T09_38_12_092Z-debug.log`:

```
9 verbose lifecycle myetherwallet@5.0.2~update:packages: CWD: /root/git/MyEtherWallet2
10 silly lifecycle myetherwallet@5.0.2~update:packages: Args: [ '-c', 'node package-test.js' ]
11 silly lifecycle myetherwallet@5.0.2~update:packages: Returned: code: 1  signal: null
12 info lifecycle myetherwallet@5.0.2~update:packages: Failed to exec update:packages script
13 verbose stack Error: myetherwallet@5.0.2 update:packages: `node package-test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid myetherwallet@5.0.2
15 verbose cwd /root/git/MyEtherWallet2
16 verbose Linux 4.4.0-17763-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "update:packages"
18 verbose node v9.11.2
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.2 update:packages: `node package-test.js`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.2 update:packages script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gamalielhere** [comment]
@DreamFlasher can you check if there's a line above the error like `new update found vue-i18n 8.8.1 8.8.2`? If so, update all the packages it says, and then rerun `npm install && npm start`

**Comment by DreamFlasher** [comment]
I eventually got it to run on an Ubuntu VM, lates dev github. It doesn't run on ubuntu bash on Windows though. In any case, good enough for me…

**Comment by danuker** [comment]
> @DreamFlasher can you check if there's a line above the error like `new update found vue-i18n 8.8.1 8.8.2`? If so, update all the packages it says, and then rerun `npm install && npm start`

Thank you! I had this problem with `bignumber.js` (8.1.1) and `stylelint-config-prettier` (5.0.0); I then updated the package versions in `package.json`, then ran the commands again, and it worked.

**Comment by garfty** [comment]
Is it possible to reopen this? I'm unable to run `npm run build`. I was going to open a new ticket but saw this. When running the command on the develop branch I get the following:

```
new update found luxon 1.11.4 1.12.0 2019-03-22T06:22:02.320Z
new update found @ledgerhq/hw-app-eth 4.47.0 4.48.0 2019-03-22T16:23:08.753Z
new update found @ledgerhq/hw-transport-u2f 4.47.0 4.48.0 2019-03-22T16:23:18.435Z
new update found copy-webpack-plugin 5.0.1 5.0.2 2019-03-22T15:52:15.342Z
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2019-03-31T14_17_17_294Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2019-03-31T14_17_17_308Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2019-03-31T14_17_17_319Z-debug.log
```

Upon looking at the logs I see this:

```
9 verbose lifecycle myetherwallet@5.0.8-hotfix.1~update:packages: CWD: /home/xxxxx/Documents/Development/Personal/Crypto/MyEtherWallet
10 silly lifecycle myetherwallet@5.0.8-hotfix.1~update:packages: Args: [ '-c', 'node package-test.js' ]
11 silly lifecycle myetherwallet@5.0.8-hotfix.1~update:packages: Returned: code: 1  signal: null
12 info lifecycle myetherwallet@5.0.8-hotfix.1~update:packages: Failed to exec update:packages script
13 verbose stack Error: myetherwallet@5.0.8-hotfix.1 update:packages: `node package-test.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/xxxxx/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/xxxxx/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid myetherwallet@5.0.8-hotfix.1
15 verbose cwd /home/xxxxx/Documents/Development/Personal/Crypto/MyEtherWallet
16 verbose Linux 4.18.12-041812-generic
17 verbose argv "/home/xxxxx/.nvm/versions/node/v10.15.3/bin/node" "/home/xxxxx/.nvm/versions/node/v10.15.3/bin/npm" "run" "update:packages"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.8-hotfix.1 update:packages: `node package-test.js`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.8-hotfix.1 update:packages script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I've tried running `npm install` again but no luck. I also tried a clean checkout and running the commands on master but with the same result.

Any help would be greatly appreciated.
Thanks

**Comment by kvhnuke** [comment]
We purposely don't let you build if there is newer version of the packages available, simply open the package.json and update the following packages

new update found luxon 1.11.4 1.12.0 2019-03-22T06:22:02.320Z
new update found @ledgerhq/hw-app-eth 4.47.0 4.48.0 2019-03-22T16:23:08.753Z
new update found @ledgerhq/hw-transport-u2f 4.47.0 4.48.0 2019-03-22T16:23:18.435Z
new update found copy-webpack-plugin 5.0.1 5.0.2 2019-03-22T15:52:15.342Z

Then do npm install and npm build :)
