### ISSUE TITLE
Error when running app in dev mode

### ISSUE THREAD

**Issue by MrLuit** [MyEtherWallet/MyEtherWallet#71]
**Node**: 8.2.1
**NPM**: 5.3.0
**Yarn**: 0.27.5

**Command**: `npm run dev`

**Error**: 
```at MemoryFileSystem.readFileSync (D:\Documenten\GitHub\MyEtherWallet\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
    at devMiddleWare.waitUntilValid (D:\Documenten\GitHub\MyEtherWallet\webpack_config\server.js:58:22)
    at Object.ready (D:\Documenten\GitHub\MyEtherWallet\node_modules\webpack-dev-middleware\lib\Shared.js:159:29)
    at Function.waitUntilValid (D:\Documenten\GitHub\MyEtherWallet\node_modules\webpack-dev-middleware\lib\Shared.js:206:10)
    at app.get (D:\Documenten\GitHub\MyEtherWallet\webpack_config\server.js:57:17)
    at Layer.handle [as handle_request] (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\layer.js:95:5)
    at D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:281:22
    at param (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:354:14)
    at param (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:410:3)
    at next (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:275:10)
    at middleware (D:\Documenten\GitHub\MyEtherWallet\node_modules\webpack-hot-middleware\middleware.js:26:48)
    at Layer.handle [as handle_request] (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:317:13)
    at D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Documenten\GitHub\MyEtherWallet\node_modules\express\lib\router\index.js:275:10)
    at goNext (D:\Documenten\GitHub\MyEtherWallet\node_modules\webpack-dev-middleware\middleware.js:27:49)
    at processRequest (D:\Documenten\GitHub\MyEtherWallet\node_modules\webpack-dev-middleware\middleware.js:58:21)```

**Comment by crptm** [comment]
Use docker on windows please
