### ISSUE TITLE
Error when building app

### ISSUE THREAD

**Issue by MrLuit** [MyEtherWallet/MyEtherWallet#72]
**Node**: 8.2.1
**NPM**: 5.3.0
**Yarn**: 0.27.5

**Command**: `npm run build`

**Error**: 
```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle MyEtherWallet@0.0.1~prebuild: MyEtherWallet@0.0.1
6 verbose lifecycle MyEtherWallet@0.0.1~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle MyEtherWallet@0.0.1~prebuild: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Documenten\GitHub\MyEtherWallet\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Programma's\Mingw\mingw32\bin;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\lib32;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\include;D:\Programma's\Cmake\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Luit\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;D:\Downloads\php-7.1.3-nts-Win32-VC14-x86;C:\ProgramData\ComposerSetup\bin;C:\Program Files\cURL\bin;C:\Go\bin;C:\Program Files (x86)\curl;C:\Ruby23\bin;C:\Users\Luit\AppData\Local\Microsoft\WindowsApps;C:\Users\Luit\AppData\Local\atom\bin;C:\Users\Luit\AppData\Local\Android\android-sdk\tools;C:\Users\Luit\AppData\Local\Android\android-sdk\platform-too;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Programma's\Mingw\mingw32\bin;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\lib32;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\include;D:\Programma's\Cmake\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Luit\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;D:\Downloads\php-7.1.3-nts-Win32-VC14-x86;C:\ProgramData\ComposerSetup\bin;C:\Program Files\cURL\bin;C:\Go\bin;C:\Program Files (x86)\curl;C:\Ruby23\bin;C:\Users\Luit\AppData\Local\Microsoft\WindowsApps;C:\Users\Luit\AppData\Local\atom\bin;C:\Users\Luit\AppData\Local\Android\android-sdk\tools;C:\Users\Luit\AppData\Local\Android\android-sdk\platform-too;C:\Users\Luit\AppData\Local\Yarn\bin
8 verbose lifecycle MyEtherWallet@0.0.1~prebuild: CWD: D:\Documenten\GitHub\MyEtherWallet
9 silly lifecycle MyEtherWallet@0.0.1~prebuild: Args: [ '/d /s /c', 'check-node-version --package' ]
10 silly lifecycle MyEtherWallet@0.0.1~prebuild: Returned: code: 0  signal: null
11 info lifecycle MyEtherWallet@0.0.1~build: MyEtherWallet@0.0.1
12 verbose lifecycle MyEtherWallet@0.0.1~build: unsafe-perm in lifecycle true
13 verbose lifecycle MyEtherWallet@0.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Documenten\GitHub\MyEtherWallet\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Programma's\Mingw\mingw32\bin;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\lib32;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\include;D:\Programma's\Cmake\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Luit\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;D:\Downloads\php-7.1.3-nts-Win32-VC14-x86;C:\ProgramData\ComposerSetup\bin;C:\Program Files\cURL\bin;C:\Go\bin;C:\Program Files (x86)\curl;C:\Ruby23\bin;C:\Users\Luit\AppData\Local\Microsoft\WindowsApps;C:\Users\Luit\AppData\Local\atom\bin;C:\Users\Luit\AppData\Local\Android\android-sdk\tools;C:\Users\Luit\AppData\Local\Android\android-sdk\platform-too;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Programma's\Mingw\mingw32\bin;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\lib32;D:\Programma's\Mingw\mingw32\i686-w64-mingw32\include;D:\Programma's\Cmake\bin;C:\Program Files (x86)\Skype\Phone\;C:\Users\Luit\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;D:\Downloads\php-7.1.3-nts-Win32-VC14-x86;C:\ProgramData\ComposerSetup\bin;C:\Program Files\cURL\bin;C:\Go\bin;C:\Program Files (x86)\curl;C:\Ruby23\bin;C:\Users\Luit\AppData\Local\Microsoft\WindowsApps;C:\Users\Luit\AppData\Local\atom\bin;C:\Users\Luit\AppData\Local\Android\android-sdk\tools;C:\Users\Luit\AppData\Local\Android\android-sdk\platform-too;C:\Users\Luit\AppData\Local\Yarn\bin
14 verbose lifecycle MyEtherWallet@0.0.1~build: CWD: D:\Documenten\GitHub\MyEtherWallet
15 silly lifecycle MyEtherWallet@0.0.1~build: Args: [ '/d /s /c',
15 silly lifecycle   'webpack --config webpack_config/webpack.prod.js' ]
16 silly lifecycle MyEtherWallet@0.0.1~build: Returned: code: 2  signal: null
17 info lifecycle MyEtherWallet@0.0.1~build: Failed to exec build script
18 verbose stack Error: MyEtherWallet@0.0.1 build: `webpack --config webpack_config/webpack.prod.js`
18 verbose stack Exit status 2
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at EventEmitter.emit (events.js:213:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:125:13)
18 verbose stack     at ChildProcess.emit (events.js:213:7)
18 verbose stack     at maybeClose (internal/child_process.js:921:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid MyEtherWallet@0.0.1
20 verbose cwd D:\Documenten\GitHub\MyEtherWallet
21 verbose Windows_NT 10.0.14393
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
23 verbose node v8.2.1
24 verbose npm  v5.3.0
25 error code ELIFECYCLE
26 error errno 2
27 error MyEtherWallet@0.0.1 build: `webpack --config webpack_config/webpack.prod.js`
27 error Exit status 2
28 error Failed at the MyEtherWallet@0.0.1 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 2, true ]
```

**Comment by dternyak** [comment]
Windows has known issues.

Try using the docker-based setup.
