### ISSUE TITLE
Clean install of MEW errors on `npm run build`.

### ISSUE THREAD

**Issue by jfarid27** [MyEtherWallet/MyEtherWallet#879]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

      Cannot build MEW from source. I'm trying to install with npm and the logs are saying it's failing at the `myetherwallet@5.0.8-hotfix.1` build.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

    1. Clone the repo and run `npm install`.
    2. Run `npm run build`.

My logs are below. It seems to be stemming around vue-cli-service build. I'm doing some experimenting and searching for this, since I'm also getting [this error]9https://npm.community/t/npm-err-cb-never-called/486/9) when locally trying `npm install`.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jalil/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/jalil/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myetherwallet@5.0.8-hotfix.1~prebuild: myetherwallet@5.0.8-hotfix.1
6 info lifecycle myetherwallet@5.0.8-hotfix.1~build: myetherwallet@5.0.8-hotfix.1
7 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: PATH: <PATH>
9 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: CWD: /home/user/Programs/MyEtherWallet
10 silly lifecycle myetherwallet@5.0.8-hotfix.1~build: Args: [ '-c', 'npm run update && vue-cli-service build' ]
11 silly lifecycle myetherwallet@5.0.8-hotfix.1~build: Returned: code: 1  signal: null
12 info lifecycle myetherwallet@5.0.8-hotfix.1~build: Failed to exec build script
13 verbose stack Error: myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid myetherwallet@5.0.8-hotfix.1
15 verbose cwd /home/user/Programs/MyEtherWallet
16 verbose Linux 4.15.0-46-generic
17 verbose argv "/home/user/.nvm/versions/node/v10.15.3/bin/node" "/home/user/.nvm/versions/node/v10.15.3/bin/npm" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.8-hotfix.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

    
  - What is the expected behavior?

     Building from source should work and not error.

  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
         Ubuntu 18.04
         Node 10.15.3
         I'm also using nvm. This may be the issue, but I don't have this problem with other projects.
    - Browser and version
        N/A
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

    So far I've tried installing/building with Node 8. Same error. Also I searched and saw it may have been a ulimit issue, but I bumped it and I'm still having an issue.

  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

    Building from source.

**Comment by NTTMai** [comment]
Same problem but my logs look like this
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hnc/.npm/_logs/2019-04-01T03_07_31_608Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hnc/.npm/_logs/2019-04-01T03_07_31_622Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@5.0.8-hotfix.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hnc/.npm/_logs/2019-04-01T03_07_31_635Z-debug.log
```

**Comment by gamalielhere** [comment]
@jfarid27 can you run `npm run update` by itself?

**Comment by NTTMai** [comment]
@gamalielhere it's ok i found my solution here, i just update all the packages   https://github.com/MyEtherWallet/MyEtherWallet/issues/671
```
We purposely don't let you build if there is newer version of the packages available, simply open the package.json and update the following packages

new update found luxon 1.11.4 1.12.0 2019-03-22T06:22:02.320Z
new update found @ledgerhq/hw-app-eth 4.47.0 4.48.0 2019-03-22T16:23:08.753Z
new update found @ledgerhq/hw-transport-u2f 4.47.0 4.48.0 2019-03-22T16:23:18.435Z
new update found copy-webpack-plugin 5.0.1 5.0.2 2019-03-22T15:52:15.342Z

Then do npm install and npm build :)
```

**Comment by jfarid27** [comment]
@gamalielhere @NTTMai I did run `npm run build` and things are getting weirder:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jalil/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/jalil/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'update' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'preupdate', 'update', 'postupdate' ]
5 info lifecycle myetherwallet@5.0.8-hotfix.1~preupdate: myetherwallet@5.0.8-hotfix.1
6 info lifecycle myetherwallet@5.0.8-hotfix.1~update: myetherwallet@5.0.8-hotfix.1
7 verbose lifecycle myetherwallet@5.0.8-hotfix.1~update: unsafe-perm in lifecycle true
8 verbose lifecycle myetherwallet@5.0.8-hotfix.1~update: PATH: /home/jalil/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jalil/Programs/MyEtherWallet/node_modules/.bin:/home/jalil/Programs/anaconda3/bin:/home/jalil/.go/bin:/home/jalil/.nvm/versions/node/v10.15.3/bin:/home/jalil/bin:/home/jalil/.local/bin:/home/jalil/bin:/home/jalil/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jalil/dotfiles/fzf/bin
9 verbose lifecycle myetherwallet@5.0.8-hotfix.1~update: CWD: /home/jalil/Programs/MyEtherWallet
10 silly lifecycle myetherwallet@5.0.8-hotfix.1~update: Args: [ '-c', 'npm run update:packages && npm run update:lists' ]
11 silly lifecycle myetherwallet@5.0.8-hotfix.1~update: Returned: code: 1  signal: null
12 info lifecycle myetherwallet@5.0.8-hotfix.1~update: Failed to exec update script
13 verbose stack Error: myetherwallet@5.0.8-hotfix.1 update: `npm run update:packages && npm run update:lists`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jalil/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/jalil/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid myetherwallet@5.0.8-hotfix.1
15 verbose cwd /home/jalil/Programs/MyEtherWallet
16 verbose Linux 4.15.0-46-generic
17 verbose argv "/home/jalil/.nvm/versions/node/v10.15.3/bin/node" "/home/jalil/.nvm/versions/node/v10.15.3/bin/npm" "run" "update"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.8-hotfix.1 update: `npm run update:packages && npm run update:lists`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.8-hotfix.1 update script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm going to try bumping node at this point and reporting back. Searching google for `node_modules/npm-lifecycle/index.js:301:16` shows a bunch of errors and nothing better than "run `npm install` with sudo" which cannot be right.

**Comment by jfarid27** [comment]
Tried with node v11.13.0 Same issue. I seem to be narrowing it down to the `npm run update` step.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jalil/.nvm/versions/node/v11.13.0/bin/node',
1 verbose cli   '/home/jalil/.nvm/versions/node/v11.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myetherwallet@5.0.8-hotfix.1~prebuild: myetherwallet@5.0.8-hotfix.1
6 info lifecycle myetherwallet@5.0.8-hotfix.1~build: myetherwallet@5.0.8-hotfix.1
7 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: PATH: /home/jalil/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jalil/Programs/MyEtherWallet/node_modules/.bin:/home/jalil/Programs/anaconda3/bin:/home/jalil/.go/bin:/home/jalil/.nvm/versions/node/v11.13.0/bin:/home/jalil/bin:/home/jalil/.local/bin:/home/jalil/bin:/home/jalil/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jalil/dotfiles/fzf/bin
9 verbose lifecycle myetherwallet@5.0.8-hotfix.1~build: CWD: /home/jalil/Programs/MyEtherWallet
10 silly lifecycle myetherwallet@5.0.8-hotfix.1~build: Args: [ '-c', 'npm run update && vue-cli-service build' ]
11 silly lifecycle myetherwallet@5.0.8-hotfix.1~build: Returned: code: 1  signal: null
12 info lifecycle myetherwallet@5.0.8-hotfix.1~build: Failed to exec build script
13 verbose stack Error: myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jalil/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/jalil/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid myetherwallet@5.0.8-hotfix.1
15 verbose cwd /home/jalil/Programs/MyEtherWallet
16 verbose Linux 4.15.0-46-generic
17 verbose argv "/home/jalil/.nvm/versions/node/v11.13.0/bin/node" "/home/jalil/.nvm/versions/node/v11.13.0/bin/npm" "run" "build"
18 verbose node v11.13.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error myetherwallet@5.0.8-hotfix.1 build: `npm run update && vue-cli-service build`
22 error Exit status 1
23 error Failed at the myetherwallet@5.0.8-hotfix.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nrg-jeff** [comment]
I'm getting the same issue @jfarid27 . Did you ever figure out the issue?

**Comment by gamalielhere** [comment]
@jfarid27 @nrg-jeff `npm run update` will stop building if you don't update the packages it points out.
run `npm run update` separately and see what packages needs to be updated before proceeding.
